### ISSUE TITLE
Remove dependency on Guava

### ISSUE THREAD

**Issue by gastaldi** [atteo/xml-combiner#8]
Although it facilitates the implementation, it would be nice if xml-combiner had no dependency on Guava, since it may conflict with other libraries that require Guava too.

**Comment by gastaldi** [comment]
Wow, that was fast! Awesome!

**Comment by gastaldi** [comment]
Can you also get rid of the `jsr305` dependency too?

**Comment by sentinelt** [comment]
fine, I will also remove jsr305

**Comment by sentinelt** [comment]
I've just released version 3.0.0 with this change. Should be in Maven Central in a few days. Have a nice day.

**Comment by gastaldi** [comment]
Fantastic! Thank you!
