### ISSUE TITLE
When combining documents, order of attributes is changed

### ISSUE THREAD

**Issue by autonomousapps** [atteo/xml-combiner#9]
It looks like they might be getting alphabetically sorted. I was **wondering if you could point me to where in the source code that might be happening.** While I understand this does not impact the semantics of the resultant XML file, I would still prefer to keep the order of attributes for better human readability. Thanks.

**Comment by sentinelt** [comment]
I believe that this is how Java XML DOM API is implemented.

See:
* https://stackoverflow.com/questions/726395/order-of-xml-attributes-after-dom-processing/3728241#3728241
* https://stackoverflow.com/questions/17725948/java-xml-library-that-preserves-attribute-order

**Comment by autonomousapps** [comment]
Thank you! I had a feeling it was the DOM code right after I asked the question. Much obliged for the pointers.
